name: Fetch Upstream

on: pull_request

jobs:
  fetch-upstream:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v1
   
